app <- ShinyDriver$new("../../")
app$snapshotInit("test-end-to-end")

app$setInputs(`cyl-cyl` = "6")
app$snapshot()
app$setInputs(`cyl-cyl` = "8")
app$snapshot()
app$setInputs(`mpg-mpg` = 14)
app$snapshot()
app$setInputs(`mpg-mpg` = 10.4)
app$snapshot()
app$setInputs(`cols-cols` = c("mpg", "cyl", "disp", "hp", "drat", "wt"))
app$setInputs(`cols-cols` = c("mpg", "cyl", "disp", "hp", "drat", "wt", "qsec"))
app$snapshot()
app$setInputs(`cols-cols` = c("mpg", "cyl", "disp", "hp", "drat", "wt"))
app$setInputs(`cols-cols` = c("mpg", "cyl", "disp", "hp", "drat"))
app$setInputs(`cols-cols` = c("mpg", "cyl", "disp", "hp"))
app$snapshot()
